# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e09ac88bfe984ff696df8a745411988454cad5e0a98c1cf4ec59d8b8b7ace1765f95915d431d79632b2e25318b371c9cddb4eabf9bf3e0cf6d3dccda1a8145c4

test:
  secret_key_base: cc7a32d6c1a691b195404212c3068eb4aa19a8773cf05d15414eb7f89116957ca0d9f9e6c50259ddc38c6480768df2e288e867e1f8648d82e01c582636c924ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
